### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by bu4ak** [Bu4ak/roles#3]

**Comment by Bu4ak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [дописать в ридми что Roles не требует таблиц](https://trello.com/c/XE1QFFbz/5-%D0%B4%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%B2-%D1%80%D0%B8%D0%B4%D0%BC%D0%B8-%D1%87%D1%82%D0%BE-roles-%D0%BD%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86)

**Comment by bu4ak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add to readme that package does not require creating tables](https://trello.com/c/XE1QFFbz/5-add-to-readme-that-package-does-not-require-creating-tables)
